<h1 align='center'><b>######### HEART MODEL CREATION ########</b></h1>

In [3]:
import pandas as pd
import numpy as np
import joblib
import warnings
warnings.filterwarnings("ignore", category=FutureWarning)
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
import random
from sklearn.model_selection import ShuffleSplit
from sklearn.model_selection import cross_validate

In [4]:
heart_data = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/Graduation Project/TheClinic/datasets /heart.csv")
heart_data.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1

In [5]:
heart_data["trestbps"]=np.log(heart_data["trestbps"])
heart_data["chol"]=np.log(heart_data["chol"])

heart_data=heart_data.drop(["fbs"],axis=1)
heart_data=heart_data.drop(["ca"],axis=1)
target=heart_data["target"]
print(heart_data.shape[1])

12

In [6]:
np.random.shuffle(heart_data.values)
heart_data=heart_data.drop(["target"],axis=1)
print(heart_data.columns)
sc= StandardScaler()
heart_data=sc.fit_transform(heart_data)

Index(['age', 'sex', 'cp', 'trestbps', 'chol', 'restecg', 'thalach', 'exang',
       'oldpeak', 'slope', 'thal'],
      dtype='object')

In [7]:
heart_model=LogisticRegression()
heart_model.fit(heart_data,target)
cv_results = cross_validate(heart_model, heart_data,target, cv=10)
print(cv_results)
joblib.dump(heart_model,"heart_model")

{'fit_time': array([0.00508571, 0.00420189, 0.00338125, 0.00352526, 0.00357223,
       0.00360179, 0.0034647 , 0.00361228, 0.00379086, 0.00382257]), 'score_time': array([0.00050592, 0.00041533, 0.0003686 , 0.00039721, 0.00039053,
       0.00036621, 0.00067902, 0.00039029, 0.00038815, 0.00037074]), 'test_score': array([0.87096774, 0.74193548, 0.87096774, 0.83333333, 0.83333333,
       0.83333333, 0.9       , 0.8       , 0.73333333, 0.83333333])}

['heart_model']