<h1 align='center'><b>##### LIVER MODEL CREATION ####</b> </h1>

In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
import random
from sklearn.model_selection import ShuffleSplit
from sklearn.model_selection import cross_validate
from imblearn.over_sampling import SMOTE
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
import joblib

In [3]:
liver_data=pd.read_csv("/content/drive/MyDrive/Colab Notebooks/Graduation Project/TheClinic/datasets /indian_liver_patient.csv")
liver_data.head()

,Age,Gender,Total_Bilirubin,Direct_Bilirubin,Alkaline_Phosphotase,Alamine_Aminotransferase,Aspartate_Aminotransferase,Total_Protiens,Albumin,Albumin_and_Globulin_Ratio,Dataset
0,65,Female,0.7,0.1,187,16,18,6.8,3.3,0.90,1
1,62,Male,10.9,5.5,699,64,100,7.5,3.2,0.74,1
2,62,Male,7.3,4.1,490,60,68,7.0,3.3,0.89,1
3,58,Male,1.0,0.4,182,14,20,6.8,3.4,1.00,1
4,72,Male,3.9,2.0,195,27,59,7.3,2.4,0.40,1

In [4]:
liver_data=liver_data.fillna(method="ffill")
liver_data.Gender=liver_data.Gender.map({"Female":1,"Male":0})
liver_data["Dataset"]=liver_data["Dataset"].map({1:0,2:1})
np.random.shuffle(liver_data.values)
print(liver_data.shape[1])
print(liver_data.columns)

11
Index(['Age', 'Gender', 'Total_Bilirubin', 'Direct_Bilirubin',
       'Alkaline_Phosphotase', 'Alamine_Aminotransferase',
       'Aspartate_Aminotransferase', 'Total_Protiens', 'Albumin',
       'Albumin_and_Globulin_Ratio', 'Dataset'],
      dtype='object')

In [5]:
target=liver_data["Dataset"]
source=liver_data.drop(["Dataset"],axis=1)

In [7]:
sm=SMOTE()
sc=StandardScaler()
liver_model=LogisticRegression()
source=sc.fit_transform(source)
X_train,X_test,y_train,y_test= train_test_split(source,target,test_size=0.01)
X_train, y_train=sm.fit_resample(X_train,y_train)
cv=cross_validate(liver_model,X_train,y_train,cv=10)
liver_model.fit(X_train,y_train)
print(cv)

{'fit_time': array([0.03465414, 0.01672554, 0.01827359, 0.03151917, 0.02118969,
       0.01601291, 0.02740788, 0.01857185, 0.02401829, 0.01880717]), 'score_time': array([0.00055265, 0.00050879, 0.00050688, 0.00066638, 0.00051475,
       0.00061989, 0.00051022, 0.00056171, 0.00051451, 0.0004797 ]), 'test_score': array([0.7195122 , 0.64634146, 0.65853659, 0.69512195, 0.6097561 ,
       0.7195122 , 0.7195122 , 0.70731707, 0.67073171, 0.82926829])}

In [8]:
joblib.dump(liver_model,"liver_model")

['liver_model']